language: node_js
node_js:
- '0.10'
before_script:
  - ./node_modules/.bin/http-server test -p 8080 &
addons:
  sauce_connect: true
env:
    global:
        - SAUCE_USERNAME=camme-webdriverjs
        - secure: lSzNpGQXV8HlReK2meTE7ySWoYnVy1n1BIln0pZGcJ0jovHpitVGnR2S/0Bu91td8agjlNUWksBR72PCSDoTQyAH105EVDVkUXkGQoKvKrdnvszGGO/aDu0Ly2Mwc47zR9BILleAtOiW+yQGd7fRdgVy1sPYPDydlUDdRpqXi0w=