language: node_js
node_js:
- '0.10'
before_script:
  - ./node_modules/.bin/http-server test -p 8080 &
addons:
  sauce_connect:
    username: "camme-webdriverjs"
    access_key:
        secure: QRHPKD3Em9atpokmy1RGTJq0QDx1VSizFs9vIhrLtWke3y5CxL7tbFZu2IZeZQziaLIyenQzouUUyLutAUsiHhhaXq6tckwq5HBY01AXlQHQQ5jaYHIPOnVjysG0r/ZCR9wCj52FGIfIuTj7moATV2AqCugdW9HBZY+/RGf3f78=