language: node_js
node_js:
- '0.10'
before_script:
  - ./node_modules/.bin/http-server test -p 8080 &
addons:
  sauce_connect: true
env:
    global:
        - SAUCE_USERNAME=camme-webdriverjs
        - secure: ZjqMA/JrUBti+RUE/9MrEvL1aqgcHQ1pH/2TfTaLbZ4651WIhKevqOcp6m5PPk8GNwp8pOpDvN1onJIKippz+HMEN9MIHubofGSK03a0PqVt9BRAiGRH3Tp51tetIPhyZY7sUn/CL3KcB9+nGCj1k4kKjEqW73KJA3igVKFo3HY=