language: node_js
node_js:
- '0.10'
before_script:
  - ./node_modules/.bin/http-server test -p 8080 &
addons:
  sauce_connect: true
env:
    global:
        - SAUCE_USERNAME=camme-webdriverjs
        - SAUCE_ACCESS_KEY=8a3aaf12-e0fa-453e-9b2d-17afadd61db9