language: node_js
node_js:
- '0.10'
before_script:
  - ./node_modules/.bin/http-server test -p 8080 &
addons:
  sauce_connect: true
env:
    global:
        - SAUCE_USERNAME=camme-webdriverjs
        - secure: GQMl+4mtPRncaJmpTYVm4Fdz25iVoA7itKfe67/b5HIpE3xIk94QxptHO+g0MVWNGYD+hnJvvsYwap/8SmA4E3gI0w8IeVkEqnEsfzO7oQN/ZtWYW+LpBce9W5Njmhb1QD/JidP2/B/6OHse64DpNYxYXVgxywjakVD7JwsPdPw=